language: go

go:
  - 1.x
  - "1.10"
  - 1.11.x
  - master

install:
  - go get -u -v github.com/kardianos/govendor
  - cd $GOPATH/src/github.com/wangsongyan && govendor sync && go install

script:
  - cd $HOME/gopath/src/github.com/wangsongyan/wblog && wblog